name: Firebase app distribution

on:
  workflow_dispatch:
    inputs:
      gitCommit:
        description: 'Git commit to distribute'
        required: true


jobs:
  print_log:
    name: Print log for commit
    runs-on: ubuntu-latest
    steps:

      - name: 'Clone repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print log
        run: |
          commit=${{ github.event.inputs.gitCommit }}
          commit_title=$(git show -s --format=%B $commit)
          echo $commit_title
          git checkout $commit
