name: Firebase app distribution

on:
  workflow_dispatch:
    inputs:
      gitCommit:
        description: 'Git commit to distribute'
        required: true


jobs:
  print_log:
    name: Print log for commit
    runs-on: ubuntu-latest
    steps:

      - name: 'Clone repository'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Print log
        run: |
          git log --oneline | cat
          commit=${{ github.event.inputs.gitCommit }}
          git show -s --format=%B $commit
          git checkout $commit

      - name: Print log next step
        run: |
          git log